#!/bin/zsh

SESSION_NAME=dotfiles
DIRECTORY=~/.dotfiles


TMUX= tmux new-session -d -s $SESSION_NAME -c $DIRECTORY

tmux split-window -h -p 10 -c $DIRECTORY
tmux select-pane -t 1
tmux send-keys -t$SESSION_NAME:1 "cd $DIRECTORY" "C-m"
tmux send-keys -t$SESSION_NAME:1 "vim" "C-m"

tmux -2 attach -t $SESSION_NAME
